# Generated by Django 2.2 on 2019-06-08 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='celular',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='jugador',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
