# Generated by Django 2.2 on 2019-07-12 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190608_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='lista',
            name='estado_derecha',
            field=models.CharField(choices=[('A', 'ABIERTA'), ('C', 'CERRADA'), ('B', 'BLOQUEADA')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='lista',
            name='estado_izquierda',
            field=models.CharField(choices=[('A', 'ABIERTA'), ('C', 'CERRADA'), ('B', 'BLOQUEADA')], default='A', max_length=1),
        ),
    ]
