# Generated by Django 2.2 on 2019-07-12 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190712_1431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lista',
            old_name='estado_derecha',
            new_name='estado_der',
        ),
        migrations.RenameField(
            model_name='lista',
            old_name='estado_izquierda',
            new_name='estado_izq',
        ),
    ]
